### ISSUE TITLE
(JS-0099) Found warning comments in code

### ISSUE THREAD

**Issue by sayak-sarkar** [1-Platform/one-platform#1217]
## Description
Developers often add comments to code that is not complete or needs review. You probably want to fix or review the code and then remove the comments before considering the code to be production-ready. Issues are raised whenever our analyzer finds these keywords in the comments i.e., TODO, FIXME, XXX. …

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/1-Platform/one-platform/issue/JS-0099/occurrences/](https://deepsource.io/gh/1-Platform/one-platform/issue/JS-0099/occurrences/)

**Comment by riginoommen** [comment]
Hi @Mr-emeka 

You can definitely work on this issue
