### ISSUE TITLE
Favicon missing and the designation of employees needs revamp and the oneplatform link is not there

### ISSUE THREAD

**Issue by hybridx** [1-Platform/one-platform#1352]
## Steps to reproduce

- Favicon is missing (redhat logo)

- the top left logo does not have a link to the home spa

- the designations of few employees has not been updated

## Expected behavior

- Updated designation, favicon added, the top left logo should have a link to the home spa

Steps to Reproduce

- Navigate to /contact-us/

## Screenshots

![contact](https://user-images.githubusercontent.com/12994292/147227094-58054f4f-350e-464d-a977-20cc70afb76f.png)

**Comment by riginoommen** [comment]
@hybridx Move this to jira why github

**Comment by hybridx** [comment]
> @hybridx Move this to jira why github

Removed the link @riginoommen 
The issue already exists in JIRA and I wanted a issue on github to keep track on github itself
