### ISSUE TITLE
Adding a rebuild flag to the deployment bash script

### ISSUE THREAD

**Issue by deshmukhmayur** [1-Platform/one-platform#505]
## Is your feature request related to a problem? Please describe

The deployment script `deploy.sh` always runs `npm run build` everytime to build a SPA. But for different environments and conditions, the build script can be different. For eg. the angular build for qa requires a `-c qa` argument, and so on.

## Describe the solution you'd like

 
A simplest solution could be to let the user build the app beforehand, and skip the build in the deploy script.

Another solution could be to provide a input argument that allows the user to enter the script that can be used for building the app, instead of `npm run build`.

## Describe alternatives you've considered

 
The alternative right now, is to fall back to building, packaging and deploying the SPA manually.

**Comment by sayak-sarkar** [comment]
`provide a input argument that allows the user to enter the script that can be used for building the app, instead of npm run build` I like this. This can be an optional attribute.

**Comment by deshmukhmayur** [comment]
We have moved away from the `build.sh` script, and migrated over to a jira build pipeline.

So closing this issue.
/close
