### ISSUE TITLE
Pull native git config to the cli

### ISSUE THREAD

**Issue by riginoommen** [1-Platform/one-platform#55]
## Is your feature request related to a problem? Please describe:

If the user skips entering the author name and author email cli should fetch the native git config for the username and user email

## Describe the solution you'd like:
execute ```git config user.email``` and ```git config user.name``` programatically

##  History
Issue derived from #44

**Comment by sayak-sarkar** [comment]
@riginoommen Is this issue already fixed?

**Comment by riginoommen** [comment]
Not yet

**Comment by hybridx** [comment]
@riginoommen Hope this helps https://github.com/1-Platform/op-components/blob/3c70373ec26a36ea22dc366cda0bfe846b3c2011/generator/generator-opc-generator/generators/app/index.js#L32

```
      {
        type: "input",
        name: "authorName",
        message: "Author Name: ",
        default: this.user.git.name()
      },
```
